services:
  derby:
    build: 
      context: .
      dockerfile: derby/Dockerfile
    volumes:
    - ./:/data
    ports:
      - "1527:1527"

  eaejava:
    build: 
      context: .
      dockerfile: Dockerfile   
    volumes:
      # Mount the project folder
      - ../:/workspace:cached
    ports:
      - "8090:8090"
    depends_on:
      - derby
